# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

plugins:
   - jekyll-paginate

host: leonov.local
port: 4001

# Site settings
title: Automatisez.net
email: info@Automatisez.net

paginate: 10

description: > # this means to ignore newlines until "baseurl:"
  Le site dédié à l'automatisation de vos tâches sur OS X et iOS. 
  Que ce soit avec Automator sur Mac, Raccourcis pour iOS ou toute autre
  solution, n'oubliez jamais que l'ordinateur est plus doué que vous pour
  les tâches répétitives.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://Automatisez.net" # the base hostname & protocol for your site
twitter_username: sgamel
github_username:  automatisez

exclude: [ "assets", "etc", "vendor", "Gemfile*" ]


# Custom variables
ibooks_link_alt: "Télécharger sur iBooks"
ibooks_link: "http://bit.ly/automatisez-sous-mac3"

# Build settings
markdown: kramdown
slogan: Le site francophone dédié à l'automatisation de vos tâches pour macOS et iOS.

defaults:
    -
        scope:
            path: ""
        values:
            header_banner: "banner-default.jpg"

sass:
    load_paths:
        - _sass
        - vendor/bundle/ruby/2.6.0/gems/bootstrap-4.6.0/assets/stylesheets/